name: Jest Tests

on: [push]
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
        env:
          CI: true
